### PR TITLE
Fix/email jurisdiction

### LINKED ISSUE #721: [Bug] Can't confirm an account
[REMEMBER: a bug should be understandable years later by someone who will never talk to the reporter or assignee.]

STEPS TO REPRODUCE:
1. Go to the public portal.
2. Try to make an account.

EXPECTED RESULTS:
Some kind of success message, along with a welcome email that is sent.

OBSERVED RESULTS:
A warning banner with a missing translation key, and no welcome email.

Screenshot from 2021-11-02 09-09-08

ADDITIONAL INFORMATION:
Debugging locally, it seems the `jurisdiction_id` is not set for translations items in the `translations` database:

```
bloom=# select * from jurisdictions;
                  id                  |         created_at         |         updated_at         |  name   | notifications_sign_up_url 
--------------------------------------+----------------------------+----------------------------+---------+---------------------------
 0454a117-8ef3-4600-bf6e-01d00dbe0e12 | 2021-11-01 16:55:14.602732 | 2021-11-01 16:55:14.602732 | Detroit | 
(1 row)

bloom=# select * from translations where jurisdiction_id='0454a117-8ef3-4600-bf6e-01d00dbe0e12';
 id | created_at | updated_at | language | translations | jurisdiction_id 
----+------------+------------+----------+--------------+-----------------
(0 rows)
```
I think it's still adding the user to the user database, but I'm not able to log in (probably because no welcome email was sent).

### PR DESCRIPTION
**Pull request by plunkettgoogle**
## Issue

- Closes #721
- [x] This change is a dependency for another issue (#701)
- [ ] This change has a dependency from another issue

## Description

Email text gets strings from the `translations` database, which are keyed on jurisdiction. If there aren't translations for the given jurisdiction, sending an email fails. This PR adds an initial seed migration to populate the `translations` database for Detroit. The seed values are obtained from the [existing seed migration](https://github.com/CityOfDetroit/bloom/blob/main/backend/core/src/migration/1620660845209-seed-translation-entries.ts).

This PR also updates the `EMAIL_FROM_ADDRESS` to the currently set sender address on our dev Sendgrid account.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Prototype/POC (not to merge)
- [ ] This change is a refactor/address technical debt
- [ ] This change requires a documentation update
- [ ] This change requires a SQL Script

## How Can This Be Tested/Reviewed?

```
$ psql bloom
bloom=# select translations.translations from translations inner join jurisdictions on translations.jurisdiction_id=jurisdictions.id and jurisdictions.name='Detroit';
```

Alternatively, set your `.env` with the correct Sendgrid `EMAIL_FROM_ADDRESS` and API key, and create an account on your local server. You should see an email being sent.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have updated the changelog to include a description of my changes
- [ ] I have run `yarn generate:client` if I made backend changes

### CODE REVIEW

File: backend/core/src/migration/1635889621244-seed-detroit-translation-entries.ts [hunk 1]
```diff
@@ -0,0 +1,68 @@
+import { MigrationInterface, QueryRunner } from "typeorm"
```
Comment (GabeBenjamin) [inline backend/core/src/migration/1635889621244-seed-detroit-translation-entries.ts:1]: Wait so there's no actual db change here? Were we just missing a migration?

Comment (plunkettgoogle) [reply backend/core/src/migration/1635889621244-seed-detroit-translation-entries.ts:1]: The "migration" (agree that it's not _really_ a migration, it's literally just adding a row) that was doing this was only inserting a row for Alameda. When we were trying to send emails with the "Detroit" jurisdiction, TranslationsService couldn't find anything.

I considered adding an entry to `detroit-seed.ts`, but figured it would be faster to follow the existing pattern.

**Review by GabeBenjamin — APPROVED** [review]
