### PR TITLE
fix: filtering on bedroom count

### LINKED ISSUE #759: [Bug] Filtering on bedroom count doesn't work
STEPS TO REPRODUCE:
1. View listings, apply filter to 0+ rooms

EXPECTED RESULTS:
All listings should be returned

OBSERVED RESULTS:
No listings are returned.

ADDITIONAL INFORMATION:
There's a stack trace in backend:
```
 BACKEND_CORE [Nest] 1973932   - 11/11/2021, 11:39:08 AM   [ExceptionsHandler] missing FROM-clause entry for table "unittyperef" +6689ms
 BACKEND_CORE QueryFailedError: missing FROM-clause entry for table "unittyperef"
 BACKEND_CORE     at new QueryFailedError (/usr/local/google/home/patplunkett/bloom/node_modules/typeorm/error/QueryFailedError.js:12:28)
 BACKEND_CORE     at PostgresQueryRunner.<anonymous> (/usr/local/google/home/patplunkett/bloom/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:248:31)
 BACKEND_CORE     at step (/usr/local/google/home/patplunkett/bloom/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
 BACKEND_CORE     at Object.throw (/usr/local/google/home/patplunkett/bloom/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
 BACKEND_CORE     at rejected (/usr/local/google/home/patplunkett/bloom/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
 BACKEND_CORE     at processTicksAndRejections (internal/process/task_queues.js:95:5)
 ```

### PR DESCRIPTION
**Pull request by plunkettgoogle**
## Issue

- Closes #759

## Description

The "bedrooms" filter type had been mis-mapped to a field after the most recent upstream merge.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Prototype/POC (not to merge)
- [ ] This change is a refactor/addresses technical debt
- [ ] This change requires a documentation update
- [ ] This change requires a SQL Script

## How Can This Be Tested/Reviewed?

Navigate to listings and apply a bedroom filter. OR:

`cd backend/core && yarn test:e2e:local --testPathPattern listings.e2e-spec --testNamePattern "Unit size filtering"`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have updated the changelog to include a description of my changes
- [ ] I have run `yarn generate:client` if I made backend changes
- [ ] I have exported any new pieces in ui-components

### CODE REVIEW

File: backend/core/src/listings/dto/filter-type-to-field-map.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ type keysWithMappedField = Exclude<
 export const filterTypeToFieldMap: Record<keysWithMappedField, string> = {
   status: "listings.status",
   name: "listings.name",
-  bedrooms: "unitTypeRef.num_bedrooms",
+  bedrooms: "summaryUnitType.num_bedrooms",
```
Comment (GabeBenjamin) [inline backend/core/src/listings/dto/filter-type-to-field-map.ts:17]: Nice find! Is this a bug in bloom's repo as well or do they have a `unitTypeRef` that we don't?

**Review by GabeBenjamin — APPROVED** [review]

File: backend/core/src/listings/dto/filter-type-to-field-map.ts (hunk 1 above)
Comment (plunkettgoogle) [reply backend/core/src/listings/dto/filter-type-to-field-map.ts:17]: We changed the name of the SQL ref in https://github.com/CityOfDetroit/bloom/pull/538. That PR was never upstreamed to bloom, so their naming is still consistent.
