### PR TITLE
[Accessibility] Fix heading hierarchy on the homepage and eligibility pages

### LINKED ISSUE #262: [Eligibility Questionnaire][Accessibility] Heading hierarchy is incorrect
There are only level 2 and level 5 headings on the page. 

This fix requires updates to the Bloom core components.

### PR DESCRIPTION
**Pull request by elenm**
## Issue

- Closes #262 
- Partially addresses #500
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description
Fixes the heading structure for the homepage and eligibility pages. See the [w3c headings article](https://www.w3.org/WAI/tutorials/page-structure/headings/) for more information on accessible headings. Headings are extremely important for screen reader users because they allow users to quickly navigate the page, and are the [primary tool](https://webaim.org/projects/screenreadersurvey8/#finding) when navigating a lengthy page. Whereas sighted users can use visual cues to quickly navigate the page, screen reader users rely on headings.

Considerations: 
* There should be at least an h1 heading on each page.
* There be no more than one h1 heading on each page. 
* Headings should not skip levels. They should be used to logically organize the content and not for styling. The eligibility page skipped h1, h3, and h4 headings and the hierarchy didn't make sense.
* I decided to make the h1 heading the document title and not the site title, because the [majority of users prefer the h1 heading to be the document title](https://webaim.org/projects/screenreadersurvey7/#heading).

This PR also makes improvements to the navigation landmarks: 
* There are 3 navigation landmarks on the home page and in the case there are [multiple landmarks](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Navigation_Role#multiple_landmarks), each should be labelled.
* The landmark label does not need to contain the word navigation, so I updated the main navigation label from "main navigation" -> "navigation". This is because the screenreader will announce the type of element and will actually read out "main navigation navigation" in the former case. 
* Translated any relevant aria-labels.

BEFORE:
Screen Shot 2021-08-30 at 6 10 15 PM
Screen Shot 2021-08-30 at 6 12 45 PM
Screen Shot 2021-09-01 at 8 38 15 PM

AFTER: 
Screen Shot 2021-08-30 at 7 12 05 PM
Screen Shot 2021-08-30 at 7 13 45 PM
Screen Shot 2021-09-01 at 8 37 11 PM

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Prototype/POC (not to merge)
- [ ] This change is a refactor/address technical debt
- [ ] This change requires a documentation update
- [ ] This change requires a SQL Script

## How Can This Be Tested/Reviewed?

Please describe the tests that you ran to verify your changes. Provide instructions so we can review. Please also list any relevant details for your test configuration

- [x] Desktop View
- [x] Mobile View
- [ ] Test A
- [ ] Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have updated the changelog to include a description of my changes
- [ ] I have run `yarn generate:client` if I made backend changes

### CODE REVIEW

**Comment by elenm** [comment]
Note that I have another PR to update the site translations #503, which I will submit before this one, so that only the translations relevant to this change are associated with the current PR.

File: ui-components/src/headers/SiteHeader.tsx [hunk 1]
```diff
@@ -66,24 +67,26 @@ const SiteHeader = (props: SiteHeaderProps) => {
...
-      <LocalizedLink
-        className={`navbar-item logo ${logoClass} ${getLogoWidthClass()}`}
-        href="/"
-        aria-label="homepage"
-      >
-        <div
-          className={`logo__lockup ${getLogoWidthClass()} ${
-            props.logoWidth && "navbar-custom-width"
-          } ${props.imageOnly && "navbar-image-only-container"}`}
+      <h2>
```
Comment (willrlin) [inline ui-components/src/headers/SiteHeader.tsx:70]: Does this component always go in the `<h2>` place? I'm wondering if it makes more sense to put the `<h2>` outside of this component so that it can be instantiated in other contexts.

File: ui-components/src/locales/ar.json [hunk 2]
```diff
@@ -571,6 +571,13 @@
         "viewApplication": "مشاهدة التطبيق",
         "yourLotteryNumber": "رقم التأكيد الخاص بك هو"
     },
+    "users": {
```
Comment (willrlin) [inline ui-components/src/locales/ar.json:574]: It looks like this change is based on top of your change to update all the strings? Please rebase once that's in so that this only has the new strings.

File: ui-components/src/locales/general.json [hunk 3]
```diff
@@ -692,6 +692,10 @@
     "noData": "No data available."
   },
   "footer": {
+    "srHeading": "Footer",
+    "srProjectInformation": "Project information",
+    "srContactInformation": "Contact information",
+    "srLegalInformation": "Legal information",
```
Comment (willrlin) [inline ui-components/src/locales/general.json:698]: What does "sr" mean in this context? I'm wondering if it might be better to just put a longer name here so it's more obvious what it is to future maintainers.

**Review by willrlin — CHANGES_REQUESTED** [review]
Please also post the changes from `ui-components` package upstream when you get a chance.

File: ui-components/src/locales/general.json (hunk 3 above)
Comment (elenm) [reply ui-components/src/locales/general.json:698]: "sr" means screen reader. The abbreviation is used by frameworks like [tailwind ](https://tailwindcss.com/docs/screen-readers)and [bootstrap](https://getbootstrap.com/docs/4.0/utilities/screenreaders/). The tailwind class "sr-only" is used in this codebase as well. Let me know if you think I should still write out the longer name.

File: ui-components/src/locales/ar.json (hunk 2 above)
Comment (elenm) [reply ui-components/src/locales/ar.json]: Done.

File: ui-components/src/headers/SiteHeader.tsx (hunk 1 above)
Comment (elenm) [reply ui-components/src/headers/SiteHeader.tsx:70]: I think the site header should always be h2 assuming we're making the document title h1. 

I do have to check some other components that also appear in the application flow before contributing upstream, because the heading order might need to be different there.

File: ui-components/src/locales/general.json (hunk 3 above)
Comment (willrlin) [reply ui-components/src/locales/general.json:698]: Ok, that's fine - probably just my unfamiliarity.

File: ui-components/src/headers/SiteHeader.tsx (hunk 1 above)
Comment (willrlin) [reply ui-components/src/headers/SiteHeader.tsx:70]: Maybe Exygy will have feedback when you post it upstream.

**Review by willrlin — APPROVED** [review]
