### PR TITLE
1252/mobile fixes

### LINKED ISSUE #1252: Detroit - assorted mobile fixes
**Assorted Fixes** 
* When I switch to Arabic and then back to English, RTL remains until refresh. It should switch automatically (Safari and Chrome on iOS)
* Add space between rent options on mobile (see image below below $450 per month and 30% income)

image

### PR DESCRIPTION
**Pull request by adriencyberspace**
## Issue #1252 

- Closes #1252 
- Addresses #issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This PR addresses two unrelated fixes -  1) a RTL fix on Safari in which the the layout wasn't switching back to LTR after going from Arabic back to non-RTL language, 2) A spacing issue between the $ per month and % income section on the listings tables,

## How Can This Be Tested/Reviewed?

Entry Point: http://localhost:3000/listings | https://detroit-public-dev.netlify.app/listings

Issue 1:
1. Visit entry point on Safari
2. Switch language to Arabic
3. Switch language back to English (or other non-RTL language)
4. Notice that page layout is properly displaying left-to-right

Issue 2:
1. On same page, minimize window to mobile width
2. Notice that there is space between the after the comma between $ per month and % income:
Screen Shot 2022-05-10 at 11 53 52 AM

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

File: sites/public/lib/helpers.tsx [hunk 1]
```diff
@@ -297,7 +297,7 @@ export const getUnitGroupSummary = (listing: Listing): UnitSummaryTable => {
     if (rentRange && rentAsPercentIncomeRange) {
       rent = (
         <>
-          {rentRange}, {rentAsPercentIncomeRange}
+          {rentRange},&nbsp;{rentAsPercentIncomeRange}
```
Comment (emilyjablonski) [inline sites/public/lib/helpers.tsx:300]: `&nbsp;` isn't always consistent amongst browsers, it would be great to see a template literal here instead

**Review by emilyjablonski — CHANGES_REQUESTED** [review]
Screen Shot 2022-05-11 at 11 35 23 AM
I'm seeing a wrapping issue with the comma for multiple rent types - not sure what is going on there but would love to resolve that :)

**Review by emilyjablonski — APPROVED** [review]
