### PR TITLE
Fix filter reset

### LINKED ISSUE #637: [Bug] Reset filter button doesn't work

### PR DESCRIPTION
**Pull request by willrlin**
## Issue

- Closes #637

## Description

A few small fixes I noticed from the deployed site:
- Filter reset button doesn't work - pass in the empty object instead of null.
- includeNulls was able to be set as an empty string in the URL, which would result in it existing as an array in the filter params - check that the value of the filter is not falsey before encoding it into the ListingFilterState object.
- Default value on the Senior Housing filter was not getting set - the default was being set to the ADA filter.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Can This Be Tested/Reviewed?

View the site and play with the filter modal.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [x] I have updated the changelog to include a description of my changes
- [x] I have run `yarn generate:client` if I made backend changes

### CODE REVIEW

File: ui-components/src/helpers/filters.ts [hunk 1]
```diff
@@ -92,7 +92,7 @@ export function decodeFiltersFromFrontendUrl(
   const filterState: ListingFilterState = {}
   let foundFilterKey = false
   for (const queryKey in query) {
-    if (queryKey in FrontendListingFilterStateKeys) {
+    if (queryKey in FrontendListingFilterStateKeys && query[queryKey]) {
```
Comment (abbiefarr) [inline ui-components/src/helpers/filters.ts:95]: I think this would prohibit using filters like "not senior housing", which we'd like to be able to do.

The purpose of deleting `data[FrontendListingFilterStateKeys.includeNulls]` in `onSubmit` was to avoid this issue, but I guess it's not WAI? Do you know how it's getting passed as an empty string?

Comment (willrlin) [reply ui-components/src/helpers/filters.ts]: Ah of course, I forgot about that case. I don't know how it was getting passed as an empty string; there was also once I was seeing it as an empty array. The deletion wasn't working because the form was passing the value as an empty array, which is truthy and thus it wouldn't be deleted. Then the param would stick around.

Comment (willrlin) [reply ui-components/src/helpers/filters.ts]: I changed to check for the empty string here; if you think we can do something about the empty array case, too, let me know.

**Review by avaleske — APPROVED** [review]
LGTM thanks for fixing this

File: ui-components/src/helpers/filters.ts (hunk 1 above)
Comment (avaleske) [reply ui-components/src/helpers/filters.ts]: We could also explicitly check for "true" and only allow that when the key is `includeNulls`

**Review by abbiefarr — APPROVED** [review]

File: ui-components/src/helpers/filters.ts (hunk 1 above)
Comment (willrlin) [reply ui-components/src/helpers/filters.ts]: I put in this as a minimum fix for now.
